Repository realm/realm-dart, pull requests merged in 2022-10, with the labels that each got.

#927 Improve doc API - deleteUser
  lib/src/app.dart
Labels: cla: yes

#932 Workaround for analyzer race issue
  CHANGELOG.md
  generator/lib/src/realm_object_generator.dart
Labels: cla: yes

#933 Address PR comments
  generator/lib/src/realm_object_generator.dart
Labels: cla: yes

#934 Add version input to the prepare release workflow
  .github/workflows/prepare-release.yml
Labels: cla: yes

#876 Add handle ownership again
  CHANGELOG.md
  common/lib/src/realm_types.dart
  lib/src/list.dart
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/realm_object.dart
  lib/src/results.dart
  lib/src/scheduler.dart
  lib/src/session.dart
  lib/src/subscription.dart
  test/configuration_test.dart
  test/list_test.dart
  test/migration_test.dart
  test/realm_object_test.dart
  test/realm_test.dart
  test/session_test.dart
  test/subscription_test.dart
Labels: cla: yes

#937 Propagate errors from initial data callback
  CHANGELOG.md
  lib/src/native/realm_core.dart
  test/configuration_test.dart
Labels: cla: yes

#946 Align metrics endpoint with java, js, kotlin and swift
  lib/src/cli/metrics/metrics_command.dart
Labels: cla: yes

#947 fix payload
  lib/src/cli/metrics/metrics_command.dart
Labels: cla: yes

#944 Add an action to enforce changelog
  .github/workflows/check-changelog.yml
  CHANGELOG.md
Labels: cla: yes

#920 Support encryption key in configuration
  CHANGELOG.md
  lib/src/configuration.dart
  lib/src/native/realm_core.dart
  test/configuration_test.dart
  test/realm_test.dart
  test/test.dart
Labels: cla: yes

#948 [Release 0.5.0+beta]
  CHANGELOG.md
  common/pubspec.yaml
  flutter/realm_flutter/example/pubspec.yaml
  flutter/realm_flutter/ios/realm.podspec
  flutter/realm_flutter/macos/realm.podspec
  flutter/realm_flutter/pubspec.yaml
  flutter/realm_flutter/tests/pubspec.yaml
  generator/pubspec.yaml
  lib/src/native/realm_core.dart
  pubspec.yaml
  src/realm_dart.cpp
Labels: cla: yes

#953 Update CHANGELOG.md
  CHANGELOG.md
Labels: cla: yes

#951 Throw better api key errors for invalid users
  CHANGELOG.md
  lib/src/user.dart
  test/user_test.dart
Labels: cla: yes

#943 Add auto assign action
  .github/auto_assign.yml
  .github/workflows/auto-assign.yml
Labels: cla: yes, no-changelog

#959 Include `DisconnectedSyncConfiguration` in reference docs
  lib/src/realm_class.dart
Labels: cla: yes

#952 fix release commit message
  .github/workflows/prepare-release.yml
Labels: cla: yes, no-changelog

#949 Don't fail workflow if publish to slack fails
  .github/workflows/publish-release.yml
Labels: cla: yes, no-changelog

#967 Fix CI update samples workflow
  .github/workflows/update-samples.yml
Labels: cla: yes, no-changelog

#969 Exit with an error code when generate command fails.
  CHANGELOG.md
  lib/src/cli/generate/generate_command.dart
Labels: cla: yes

#962 add a test for working encryption
  lib/src/configuration.dart
  test/configuration_test.dart
  test/realm_test.dart
Labels: cla: yes, no-changelog

#965 CI actions - fixed Node16
  .github/workflows/auto-assign.yml
  .github/workflows/binary-combine-android.yml
  .github/workflows/binary-combine-ios.yml
  .github/workflows/build-native.yml
  .github/workflows/check-changelog.yml
  .github/workflows/ci.yml
  .github/workflows/dart-desktop-tests.yml
  .github/workflows/flutter-desktop-tests.yml
  .github/workflows/prepare-release.yml
  .github/workflows/publish-release.yml
Labels: cla: yes, no-changelog

#972 Bump json_annotation version to fix generator tests
  flutter/realm_flutter/pubspec.yaml
  lib/src/cli/metrics/metrics.g.dart
  pubspec.yaml
Labels: cla: yes, no-changelog

#731 Open realm async
  CHANGELOG.md
  ffigen/README.md
  flutter/realm_flutter/pubspec.yaml
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/session.dart
  pubspec.yaml
  test/configuration_test.dart
  test/realm_test.dart
  test/subscription_test.dart
  test/test.dart
  test/test.g.dart
Labels: cla: yes

#978 Improve robustness of API key tests
  lib/src/cli/metrics/metrics.g.dart
  test/test.dart
  test/user_test.dart
Labels: cla: yes, no-changelog

#975 Port embedded object support to master
  CHANGELOG.md
  common/lib/src/realm_common_base.dart
  common/lib/src/realm_types.dart
  example/bin/myapp.g.dart
  flutter/realm_flutter/example/lib/main.g.dart
  flutter/realm_flutter/tests/test_driver/realm_test.dart
  generator/lib/src/class_element_ex.dart
  generator/lib/src/realm_field_info.dart
  generator/lib/src/realm_model_info.dart
  generator/test/error_test_data/embedded_object_primary_key.dart
  generator/test/error_test_data/embedded_object_primary_key.expected
  generator/test/good_test.dart
  generator/test/good_test_data/all_types.expected
  generator/test/good_test_data/embedded_annotations.dart
  generator/test/good_test_data/embedded_annotations.expected
  generator/test/good_test_data/embedded_objects.dart
  generator/test/good_test_data/embedded_objects.expected
  generator/test/good_test_data/list_initialization.expected
  generator/test/good_test_data/mapto.expected
  generator/test/good_test_data/optional_argument.expected
  generator/test/good_test_data/pinhole.expected
  generator/test/good_test_data/primary_key.expected
  generator/test/good_test_data/required_argument.expected
  generator/test/good_test_data/required_argument_with_default_value.expected
  generator/test/good_test_data/user_defined_getter.expected
  lib/src/cli/atlas_apps/baas_client.dart
  lib/src/configuration.dart
  lib/src/list.dart
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/realm_object.dart
  lib/src/realm_property.dart
  lib/src/results.dart
  test/dynamic_realm_test.dart
  test/embedded_test.dart
  test/list_test.dart
  test/migration_test.dart
  test/migration_test.g.dart
  test/realm_object_test.dart
  test/realm_object_test.g.dart
  test/test.dart
  test/test.g.dart
  test/user_test.dart
Labels: cla: yes

#980 [Release 0.6.0+beta]
  CHANGELOG.md
  common/pubspec.yaml
  flutter/realm_flutter/example/pubspec.yaml
  flutter/realm_flutter/ios/realm.podspec
  flutter/realm_flutter/macos/realm.podspec
  flutter/realm_flutter/pubspec.yaml
  flutter/realm_flutter/tests/pubspec.yaml
  generator/pubspec.yaml
  lib/src/native/realm_core.dart
  pubspec.yaml
  src/realm_dart.cpp
Labels: cla: yes

#982 Generator fixes
  .vscode/launch.json
  generator/README.md
  generator/lib/src/class_element_ex.dart
  generator/lib/src/field_element_ex.dart
  generator/test/test_util.dart
Labels: cla: yes, no-changelog

#985 Unsubscribe by type
  CHANGELOG.md
  lib/src/subscription.dart
  test/subscription_test.dart
Labels: cla: yes

#984 Don't assume api key order in fetchAll
  test/user_test.dart
Labels: cla: yes, no-changelog

#990 sync readme
  README.md
Labels: cla: yes, no-changelog

#973 Atlas functions support
  CHANGELOG.md
  ffigen/README.md
  lib/src/cli/atlas_apps/baas_client.dart
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/user.dart
  test/app_test.dart
Labels: cla: yes

#983 Reorder AuthProviderType values
  CHANGELOG.md
  lib/src/credentials.dart
  lib/src/native/realm_core.dart
  test/credentials_test.dart
Labels: cla: yes, no-changelog

#993 fix up readme
  README.md
Labels: cla: yes, no-changelog

#997 User.functions changelog
  CHANGELOG.md
Labels: cla: yes

#996 Backlink support
  .vscode/settings.json
  CHANGELOG.md
  common/lib/src/realm_common_base.dart
  generator/lib/src/class_element_ex.dart
  generator/lib/src/dart_type_ex.dart
  generator/lib/src/element.dart
  generator/lib/src/error.dart
  generator/lib/src/field_element_ex.dart
  generator/lib/src/format_spans.dart
  generator/lib/src/pseudo_type.dart
  generator/lib/src/realm_field_info.dart
  generator/lib/src/realm_model_info.dart
  generator/lib/src/session.dart
  generator/lib/src/type_checkers.dart
  generator/pubspec.yaml
  generator/test/error_test.dart
  generator/test/error_test_data/backlink_annotation_on_incompatible_field.dart
  generator/test/error_test_data/backlink_annotation_on_incompatible_field.expected
  generator/test/error_test_data/backlink_annotation_on_invalid_iterable.dart
  generator/test/error_test_data/backlink_annotation_on_invalid_iterable.expected
  generator/test/error_test_data/backlink_illegal_symbol.dart
  generator/test/error_test_data/backlink_illegal_symbol.expected
  generator/test/error_test_data/backlink_incompatible_type.dart
  generator/test/error_test_data/backlink_incompatible_type.expected
  generator/test/error_test_data/backlink_unknown_symbol.dart
  generator/test/error_test_data/backlink_unknown_symbol.expected
  generator/test/error_test_data/invalid_model_name_mapping.expected
  generator/test/error_test_data/missing_underscore.g.dart
  generator/test/good_test_data/all_types.dart
  generator/test/good_test_data/all_types.expected
  generator/test/test_util.dart
  lib/src/native/realm_core.dart
  lib/src/realm_object.dart
  lib/src/realm_property.dart
  test/backlinks_test.dart
  test/backlinks_test.g.dart
Labels: cla: yes

#998 Add timeouts for CI jobs
  .github/workflows/binary-combine-android.yml
  .github/workflows/binary-combine-ios.yml
  .github/workflows/build-native.yml
  .github/workflows/check-changelog.yml
  .github/workflows/ci.yml
  .github/workflows/dart-desktop-tests.yml
  .github/workflows/flutter-desktop-tests.yml
Labels: no-changelog

#999 Set the correct schema mode for disconnectedSync
  CHANGELOG.md
  lib/src/native/realm_core.dart
Labels: cla: yes
