Repository realm/realm-dart, pull requests merged in 2023-06, with the labels that each got.

#1232 Send Slack message if the CI fails on main branch
  .github/workflows/ci.yml
  .github/workflows/dart-desktop-tests.yml
Labels: cla: yes, no-changelog

#1269 refactor tests
  lib/src/cli/atlas_apps/baas_client.dart
  lib/src/native/realm_core.dart
  src/realm_dart.cpp
  test/app_test.dart
  test/client_reset_test.dart
  test/realm_test.dart
  test/test.dart
Labels: cla: yes, no-changelog

#1300 Add support for FTS
  CHANGELOG.md
  common/lib/src/realm_common_base.dart
  common/lib/src/realm_types.dart
  generator/lib/src/field_element_ex.dart
  generator/lib/src/realm_field_info.dart
  generator/lib/src/realm_model_info.dart
  generator/test/error_test_data/bool_not_allowed_as_primary_key.expected
  generator/test/error_test_data/date_primary_key.dart
  generator/test/error_test_data/date_primary_key.expected
  generator/test/error_test_data/fts_index_wrong_type.dart
  generator/test/error_test_data/fts_index_wrong_type.expected
  generator/test/error_test_data/not_an_indexable_type.expected
  generator/test/error_test_data/realm_value_not_allowed_as_primary_key.expected
  generator/test/good_test_data/all_types.expected
  generator/test/good_test_data/embedded_annotations.expected
  generator/test/good_test_data/indexable_types.dart
  generator/test/good_test_data/indexable_types.expected
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/realm_property.dart
  test/indexed_test.dart
  test/indexed_test.g.dart
  test/realm_value_test.g.dart
Labels: cla: yes

#1306 Bump version of Dart >=3.0.2 and Flutter >=3.10.2
  CHANGELOG.md
  common/pubspec.yaml
  example/pubspec.yaml
  ffigen/pubspec.yaml
  flutter/realm_flutter/example/pubspec.yaml
  flutter/realm_flutter/pubspec.yaml
  flutter/realm_flutter/tests/pubspec.yaml
  flutter/realm_flutter/tests/windows/runner/Runner.rc
  generator/pubspec.yaml
  lib/src/native/decimal128.dart
  lib/src/native/realm_bindings.dart
  pubspec.yaml
Labels: cla: yes

#1309 remove debug left over from tests
  test/test.dart
Labels: no-changelog

#1311 Add attempt id to slack link
  .github/workflows/ci.yml
Labels: cla: yes

#1314 [Release 1.2.0]
  CHANGELOG.md
  common/pubspec.yaml
  example/pubspec.yaml
  ffigen/pubspec.yaml
  flutter/realm_flutter/example/pubspec.yaml
  flutter/realm_flutter/ios/realm.podspec
  flutter/realm_flutter/macos/realm.podspec
  flutter/realm_flutter/pubspec.yaml
  flutter/realm_flutter/tests/pubspec.yaml
  flutter/realm_flutter/tests/windows/runner/Runner.rc
  generator/pubspec.yaml
  lib/src/cli/metrics/metrics_command.dart
  lib/src/native/decimal128.dart
  lib/src/native/realm_bindings.dart
  lib/src/native/realm_core.dart
  pubspec.yaml
  src/realm_dart.cpp
Labels: cla: yes

#1320 binary type support
  CHANGELOG.md
  common/lib/src/realm_types.dart
  generator/lib/src/dart_type_ex.dart
  generator/lib/src/field_element_ex.dart
  generator/lib/src/realm_model_info.dart
  generator/test/good_test_data/all_types.expected
  generator/test/good_test_data/binary_type.dart
  generator/test/good_test_data/binary_type.expected
  lib/src/native/realm_core.dart
  test/realm_object_test.dart
  test/realm_set_test.dart
  test/realm_set_test.g.dart
  test/realm_value_test.dart
  test/test.dart
  test/test.g.dart
Labels: cla: yes

#1293 Backlinks getters throws for unmanaged objects
  CHANGELOG.md
  generator/lib/src/realm_field_info.dart
  generator/test/good_test_data/all_types.expected
  test/backlinks_test.dart
  test/backlinks_test.g.dart
  test/realm_test.dart
Labels: cla: yes

#1325 fix metrics on Windows and use dart pub instead of `flutter pub`
  .github/workflows/ci.yml
  .github/workflows/flutter-desktop-tests.yml
  flutter/realm_flutter/android/build.gradle
  flutter/realm_flutter/ios/realm.podspec
  flutter/realm_flutter/ios/realm_dev.podspec
  flutter/realm_flutter/linux/CMakeLists.txt
  flutter/realm_flutter/macos/realm.podspec
  flutter/realm_flutter/windows/CMakeLists.txt
  lib/src/cli/metrics/metrics_command.dart
Labels: cla: yes, no-changelog

#1329 Bump `http` package version ^1.0.0
  flutter/realm_flutter/pubspec.yaml
  pubspec.yaml
Labels: cla: yes, no-changelog

#1330 [Release 1.3.0]
  CHANGELOG.md
  common/pubspec.yaml
  flutter/realm_flutter/example/pubspec.yaml
  flutter/realm_flutter/ios/realm.podspec
  flutter/realm_flutter/macos/realm.podspec
  flutter/realm_flutter/pubspec.yaml
  flutter/realm_flutter/tests/pubspec.yaml
  generator/pubspec.yaml
  lib/src/cli/metrics/metrics_command.dart
  lib/src/native/realm_core.dart
  pubspec.yaml
  src/realm_dart.cpp
Labels: cla: yes

#1332 Update cancellation_token
  README.md
  flutter/realm_flutter/pubspec.yaml
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/set.dart
  pubspec.yaml
Labels: cla: yes, no-changelog

#1335 Fix double unlock, and lock order race
  CHANGELOG.md
  src/realm_dart_sync.cpp
Labels: cla: yes

#1336 New SVG logo
  README.md
  logo.png
  media/favicon.ico
  media/logo-dark.svg
  media/logo.svg
Labels: cla: yes

#1337 Guard against spurious awakes
  CHANGELOG.md
  src/realm_dart_sync.cpp
Labels: cla: yes
