Repository realm/realm-dart, pull requests merged in 2024-05, with the labels that each got.

#1652 RDART-950: Update nullability annotations for base url API
  CHANGELOG.md
  packages/realm_dart/lib/src/app.dart
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/test/app_test.dart
  packages/realm_dart/test/baas_helper.dart
  packages/realm_dart/test/test.dart
Labels: cla: yes

#1658 RDART-1016: Cleanup iOS podspec
  CHANGELOG.md
  packages/realm/ios/realm.podspec
Labels: cla: yes

#1659 [Release 2.2.1]
  CHANGELOG.md
  packages/realm/example/pubspec.yaml
  packages/realm/ios/realm.podspec
  packages/realm/macos/realm.podspec
  packages/realm/pubspec.yaml
  packages/realm_common/pubspec.yaml
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/pubspec.yaml
  packages/realm_dart/src/realm_dart.cpp
  packages/realm_generator/pubspec.yaml
Labels: cla: yes, no-jira-ticket

#1664 RDART-1018: Fix badly generated _fromJson
  CHANGELOG.md
  packages/realm_generator/lib/src/realm_model_info.dart
  packages/realm_generator/test/good_test_data/private_fields.expected
Labels: cla: yes

#1669 RDART-1021: Wire up some basic dynamic setting and change notifications
  CHANGELOG.md
  packages/realm_dart/lib/src/realm_class.dart
  packages/realm_dart/lib/src/realm_object.dart
  packages/realm_dart/test/dynamic_realm_test.dart
  packages/realm_dart/test/test.dart
  packages/realm_dart/test/test.realm.dart
Labels: cla: yes

#1683 RDART-1028: Use Zone.current.bindUnaryCallbackGuarded for RawReceivePort.handler
  CHANGELOG.md
  packages/realm_dart/lib/src/scheduler.dart
Labels: cla: yes

#1686 [Release 2.3.0]
  CHANGELOG.md
  packages/realm/example/pubspec.yaml
  packages/realm/ios/realm.podspec
  packages/realm/macos/realm.podspec
  packages/realm/pubspec.yaml
  packages/realm_common/pubspec.yaml
  packages/realm_dart/lib/src/cli/metrics/metrics_command.dart
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/pubspec.yaml
  packages/realm_dart/src/realm_dart.cpp
  packages/realm_generator/pubspec.yaml
Labels: cla: yes, no-jira-ticket

#1691 RDART-1038: Drop keep alive hack
  CHANGELOG.md
  packages/realm_dart/lib/src/app.dart
  packages/realm_dart/lib/src/collections.dart
  packages/realm_dart/lib/src/configuration.dart
  packages/realm_dart/lib/src/credentials.dart
  packages/realm_dart/lib/src/list.dart
  packages/realm_dart/lib/src/map.dart
  packages/realm_dart/lib/src/native/handle_base.dart
  packages/realm_dart/lib/src/realm_class.dart
  packages/realm_dart/lib/src/realm_object.dart
  packages/realm_dart/lib/src/results.dart
  packages/realm_dart/lib/src/session.dart
  packages/realm_dart/lib/src/set.dart
  packages/realm_dart/lib/src/subscription.dart
  packages/realm_dart/lib/src/user.dart
Labels: cla: yes

#1696 RDART-1039: Drop catalyst support. Flutter doesn't support it
  .github/workflows/binary-combine-ios.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  packages/realm_dart/CMakePresets.json
  packages/realm_dart/dev/lib/src/build.dart
  packages/realm_dart/scripts/build-ios.sh
Labels: cla: yes

#1548 RDART-962: Use xcode 15.4
  .github/workflows/binary-combine-android.yml
  .github/workflows/build-native.yml
  .github/workflows/ci.yml
  .github/workflows/dart-desktop-tests.yml
  .github/workflows/flutter-desktop-tests.yml
  CHANGELOG.md
  packages/realm_dart/CMakePresets.json
  packages/realm_dart/scripts/build-macos.sh
Labels: cla: yes

#1700 RDART-1045: Expose setrlimit ios
  .github/workflows/ci.yml
  packages/realm_dart/lib/src/native/realm_bindings.dart
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/src/ios/platform.mm
  packages/realm_dart/src/realm_dart.h
  packages/realm_dart/test/test.dart
Labels: cla: yes, no-changelog

#1623 RDART-999: Fix flutter test dlopen
  CHANGELOG.md
  packages/realm_dart/lib/src/cli/common/target_os_type.dart
  packages/realm_dart/lib/src/cli/install/install_command.dart
  packages/realm_dart/lib/src/cli/install/options.dart
  packages/realm_dart/lib/src/cli/install/options.g.dart
  packages/realm_dart/lib/src/init.dart
  packages/realm_dart/lib/src/realm_dart.dart
  packages/realm_dart/lib/src/realm_flutter.dart
Labels: cla: yes

#1666 RDART-1020: Fix writeAsync behaviour
  CHANGELOG.md
  packages/realm_dart/lib/src/realm_class.dart
  packages/realm_dart/test/realm_test.dart
Labels: cla: yes
