Repository realm/realm-dart, pull requests merged in 2024-04, with the labels that each got.

#1612 RDART-992: Handle Identifer expression as well
  packages/realm_generator/lib/src/field_element_ex.dart
  packages/realm_generator/test/good_test_data/const_initializer.dart
  packages/realm_generator/test/good_test_data/const_initializer.expected
Labels: cla: yes, no-changelog

#1613 RDART-991: Rename Key enum
  packages/CHANGELOG.ejson.md
  packages/ejson/lib/src/decoding.dart
  packages/ejson/lib/src/encoding.dart
  packages/ejson/lib/src/types.dart
  packages/ejson/pubspec.yaml
  packages/ejson/test/ejson_test.dart
  packages/ejson_analyzer/pubspec.yaml
  packages/ejson_annotation/pubspec.yaml
  packages/ejson_generator/pubspec.yaml
  packages/ejson_lint/example/pubspec.yaml
  packages/ejson_lint/pubspec.yaml
  packages/realm_dart/pubspec.yaml
Labels: cla: yes, no-changelog

#1614 RDART-983: Refactor how we open dynamic library to give better error message
  CHANGELOG.md
  packages/realm_dart/lib/src/init.dart
Labels: cla: yes

#1608 Update README.md
  README.md
Labels: cla: yes

#1617 RDART-996: Don't serialize backlinks
  CHANGELOG.md
  packages/realm_dart/test/backlinks_test.dart
  packages/realm_dart/test/backlinks_test.realm.dart
  packages/realm_generator/lib/src/realm_model_info.dart
  packages/realm_generator/test/good_test_data/all_types.expected
Labels: cla: yes

#1620 RDART-963: Update to new base url
  CHANGELOG.md
  packages/realm_dart/lib/src/app.dart
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/test/app_test.dart
Labels: cla: yes

#1622 RDART-987: Schema migration support follow-up
  .github/workflows/publish-release.yml
  packages/realm_dart/test/baas_helper.dart
Labels: cla: yes, no-changelog, no-jira-ticket

#1585 RDART-980: Add tests for collections in `Mixed` with synced realms
  packages/realm_dart/test/realm_value_test.dart
  packages/realm_dart/test/realm_value_test.realm.dart
  packages/realm_dart/test/session_test.dart
  packages/realm_dart/test/sync_migration_test.dart
  packages/realm_dart/test/test.dart
  packages/realm_dart/test/test.realm.dart
Labels: cla: yes, no-changelog

#1635 RDART-852: Allow private fields on models
  CHANGELOG.md
  packages/realm_generator/lib/src/field_element_ex.dart
  packages/realm_generator/pubspec.yaml
  packages/realm_generator/test/good_test_data/private_fields.dart
  packages/realm_generator/test/good_test_data/private_fields.expected
  packages/realm_generator/test/good_test_data/private_fields.realm.dart
Labels: cla: yes

#1628 RDART-1007: Compare 8 bytes at a time for Uint8Lists
  CHANGELOG.md
  packages/realm_common/lib/src/realm_types.dart
  packages/realm_dart/test/realm_value_test.dart
Labels: cla: yes

#1633 RDART-1006: Reference equality implies equality
  CHANGELOG.md
  packages/realm_common/lib/src/realm_types.dart
  packages/realm_dart/test/realm_value_test.dart
Labels: cla: yes

#1601 [RDART-968] Add support for keypath filtering on object
  CHANGELOG.md
  packages/realm/example/lib/main.realm.dart
  packages/realm_dart/example/bin/myapp.realm.dart
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/lib/src/realm_object.dart
  packages/realm_dart/test/backlinks_test.realm.dart
  packages/realm_dart/test/dynamic_realm_test.realm.dart
  packages/realm_dart/test/geospatial_test.realm.dart
  packages/realm_dart/test/indexed_test.realm.dart
  packages/realm_dart/test/migration_test.realm.dart
  packages/realm_dart/test/realm_map_test.realm.dart
  packages/realm_dart/test/realm_object_test.dart
  packages/realm_dart/test/realm_object_test.realm.dart
  packages/realm_dart/test/realm_set_test.realm.dart
  packages/realm_dart/test/realm_value_test.realm.dart
  packages/realm_dart/test/sync_migration_test.realm.dart
  packages/realm_dart/test/test.realm.dart
  packages/realm_generator/lib/src/realm_model_info.dart
  packages/realm_generator/test/good_test_data/all_types.expected
  packages/realm_generator/test/good_test_data/another_mapto.expected_multi
  packages/realm_generator/test/good_test_data/asymmetric_object.expected
  packages/realm_generator/test/good_test_data/binary_type.expected
  packages/realm_generator/test/good_test_data/const_initializer.expected
  packages/realm_generator/test/good_test_data/embedded_annotations.expected
  packages/realm_generator/test/good_test_data/embedded_objects.expected
  packages/realm_generator/test/good_test_data/indexable_types.expected
  packages/realm_generator/test/good_test_data/list_initialization.expected
  packages/realm_generator/test/good_test_data/map.expected
  packages/realm_generator/test/good_test_data/mapto.expected
  packages/realm_generator/test/good_test_data/optional_argument.expected
  packages/realm_generator/test/good_test_data/pinhole.expected
  packages/realm_generator/test/good_test_data/primary_key.expected
  packages/realm_generator/test/good_test_data/realm_set.expected
  packages/realm_generator/test/good_test_data/required_argument.expected
  packages/realm_generator/test/good_test_data/required_argument_with_default_value.expected
  packages/realm_generator/test/good_test_data/user_defined_getter.expected
Labels: cla: yes

#1641 RDART-1010: Allow configuration of generator per realm model class
  CHANGELOG.md
  packages/realm_common/lib/src/realm_common_base.dart
  packages/realm_common/lib/src/realm_types.dart
  packages/realm_generator/lib/src/class_element_ex.dart
  packages/realm_generator/lib/src/dart_type_ex.dart
  packages/realm_generator/lib/src/realm_model_info.dart
  packages/realm_generator/test/good_test_data/all_named_ctor.dart
  packages/realm_generator/test/good_test_data/all_named_ctor.expected
  packages/realm_generator/test/good_test_data/all_named_ctor.realm.dart
  packages/realm_generator/test/good_test_data/private_fields.expected
Labels: cla: yes

#1649 Don't downgrade xcode
  .github/workflows/build-native.yml
Labels: cla: yes

#1648 RDART-1014: Bump required sdk version to ^3.3.0
  CHANGELOG.md
  melos.yaml
  packages/ejson/pubspec.yaml
  packages/ejson_analyzer/pubspec.yaml
  packages/ejson_annotation/pubspec.yaml
  packages/ejson_generator/pubspec.yaml
  packages/ejson_lint/example/pubspec.yaml
  packages/ejson_lint/pubspec.yaml
  packages/realm/example/pubspec.yaml
  packages/realm/pubspec.yaml
  packages/realm/tests/pubspec.yaml
  packages/realm_common/pubspec.yaml
  packages/realm_dart/example/pubspec.yaml
  packages/realm_dart/pubspec.yaml
  packages/realm_generator/pubspec.yaml
Labels: cla: yes

#1646 RDART-964: Add PrivacyInfo.xcprivacy for iOS and macOS
  CHANGELOG.md
  packages/realm/ios/Resources/PrivacyInfo.xcprivacy
  packages/realm/ios/realm.podspec
  packages/realm/macos/Resources/PrivacyInfo.xcprivacy
  packages/realm/macos/realm.podspec
Labels: cla: yes
