Repository realm/realm-dart, pull requests merged in 2024-03, with the labels that each got.

#1533 Add support for dynamic.getSet/getMap
  CHANGELOG.md
  packages/realm_dart/lib/src/realm_object.dart
  packages/realm_dart/test/dynamic_realm_test.dart
  packages/realm_dart/test/list_test.dart
  packages/realm_dart/test/realm_object_test.dart
  packages/realm_dart/test/test.dart
  packages/realm_dart/test/test.realm.dart
Labels: cla: yes

#1539 RPM-568: Add a workflow that verifies PR title
  .github/workflows/check-pr-title.yml
Labels: cla: yes, no-changelog

#1543 RDART-960 Fix generated _fromEJson on Realm models
  packages/realm_dart/test/backlinks_test.realm.dart
  packages/realm_dart/test/dynamic_realm_test.dart
  packages/realm_dart/test/geospatial_test.realm.dart
  packages/realm_dart/test/realm_map_test.realm.dart
  packages/realm_dart/test/realm_object_test.dart
  packages/realm_dart/test/realm_set_test.realm.dart
  packages/realm_dart/test/realm_value_test.realm.dart
  packages/realm_dart/test/results_test.dart
  packages/realm_dart/test/test.dart
  packages/realm_dart/test/test.realm.dart
  packages/realm_dart/tool/build.dart
  packages/realm_generator/lib/src/field_element_ex.dart
  packages/realm_generator/lib/src/realm_field_info.dart
  packages/realm_generator/lib/src/realm_model_info.dart
  packages/realm_generator/test/error_test_data/const_initializer.dart
  packages/realm_generator/test/error_test_data/const_initializer.expected
  packages/realm_generator/test/error_test_data/const_initializer.realm.dart
  packages/realm_generator/test/good_test_data/all_types.dart
  packages/realm_generator/test/good_test_data/all_types.expected
  packages/realm_generator/test/good_test_data/another_mapto.expected_multi
  packages/realm_generator/test/good_test_data/asymmetric_object.expected
  packages/realm_generator/test/good_test_data/binary_type.dart
  packages/realm_generator/test/good_test_data/binary_type.expected
  packages/realm_generator/test/good_test_data/embedded_annotations.expected
  packages/realm_generator/test/good_test_data/embedded_objects.expected
  packages/realm_generator/test/good_test_data/list_initialization.expected
  packages/realm_generator/test/good_test_data/map.expected
  packages/realm_generator/test/good_test_data/mapto.expected
  packages/realm_generator/test/good_test_data/realm_set.expected
Labels: cla: yes, no-changelog

#1544 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/check-pr-title.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#1555 RDART-971: Prepare ejson packages
  .github/workflows/prepare-release.yml
  .github/workflows/publish-release.yml
  analysis_options.yaml
  melos.yaml
  packages/CHANGELOG.ejson.md
  packages/README.ejson.md
  packages/ejson/CHANGELOG.md
  packages/ejson/README.md
  packages/ejson/lib/src/types.dart
  packages/ejson/pubspec.yaml
  packages/ejson_analyzer/CHANGELOG.md
  packages/ejson_analyzer/README.md
  packages/ejson_analyzer/pubspec.yaml
  packages/ejson_annotation/CHANGELOG.md
  packages/ejson_annotation/README.md
  packages/ejson_annotation/pubspec.yaml
  packages/ejson_generator/CHANGELOG.md
  packages/ejson_generator/README.md
  packages/ejson_generator/pubspec.yaml
  packages/ejson_lint/CHANGELOG.md
  packages/ejson_lint/README.md
  packages/ejson_lint/example/pubspec.yaml
  packages/ejson_lint/pubspec.yaml
  packages/realm/example/pubspec.yaml
  packages/realm/pubspec.yaml
  packages/realm_dart/dev/CHANGELOG.md
  packages/realm_dart/dev/README.md
  packages/realm_dart/dev/analysis_options.yaml
  packages/realm_dart/dev/bin/dev.dart
  packages/realm_dart/dev/lib/dev.dart
  packages/realm_dart/dev/lib/src/build.dart
  packages/realm_dart/dev/pubspec.yaml
  packages/realm_dart/pubspec.yaml
Labels: cla: yes, no-changelog

#1563 RDART-972: Prepare breaking change for progress notifications
  CHANGELOG.md
  packages/realm_dart/lib/src/session.dart
  packages/realm_dart/test/realm_test.dart
  packages/realm_dart/test/session_test.dart
Labels: cla: yes

#1554 RDART-941: Clear collections in mixed when reassigned
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/test/realm_value_test.dart
Labels: cla: yes, no-changelog

#1567 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/lock-threads.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#1569 [Release 2.0.0-alpha.4]
  .github/workflows/prepare-release.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
  packages/realm/example/pubspec.yaml
  packages/realm/ios/realm.podspec
  packages/realm/macos/realm.podspec
  packages/realm/pubspec.yaml
  packages/realm_common/pubspec.yaml
  packages/realm_dart/lib/src/cli/metrics/metrics_command.dart
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/pubspec.yaml
  packages/realm_dart/src/realm_dart.cpp
  packages/realm_generator/pubspec.yaml
Labels: cla: yes, no-jira-ticket

#1570 [Release 2.0.0-alpha.5]
  .github/workflows/publish-release.yml
  CHANGELOG.md
  packages/realm/example/pubspec.yaml
  packages/realm/ios/realm.podspec
  packages/realm/macos/realm.podspec
  packages/realm/pubspec.yaml
  packages/realm_common/pubspec.yaml
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/pubspec.yaml
  packages/realm_dart/src/realm_dart.cpp
  packages/realm_generator/pubspec.yaml
Labels: cla: yes, no-jira-ticket

#1573 Cleanup changelog, bring back melos publishing
  .github/workflows/publish-release.yml
  CHANGELOG.md
Labels: cla: yes, no-jira-ticket

#1571 Update build instructions and switching Flutter/Dart versions
  CONTRIBUTING.md
  media/vscode-switch-dart-version.png
Labels: cla: yes, no-changelog, no-jira-ticket

#1576 RDART-976: Fix install command
  packages/realm_dart/lib/src/cli/install/install_command.dart
Labels: cla: yes, no-changelog

#1581 RDART-978: Add support RealmValue.fromJson
  CHANGELOG.md
  packages/realm_common/lib/src/realm_types.dart
  packages/realm_dart/test/realm_value_test.dart
Labels: cla: yes

#1587 Update melos to 5.2.0
  melos.yaml
  pubspec.yaml
Labels: cla: yes, no-changelog, no-jira-ticket

#1591 Wrong test for local development
  CHANGELOG.md
  packages/realm/macos/realm.podspec
Labels: cla: yes, no-changelog

#1592 Cleanup the changelog for 2.0.0
  CHANGELOG.md
Labels: cla: yes

#1593 [Release 2.0.0]
  CHANGELOG.md
  packages/realm/example/pubspec.yaml
  packages/realm/ios/realm.podspec
  packages/realm/macos/realm.podspec
  packages/realm/pubspec.yaml
  packages/realm_common/pubspec.yaml
  packages/realm_dart/lib/src/native/realm_core.dart
  packages/realm_dart/pubspec.yaml
  packages/realm_dart/src/realm_dart.cpp
  packages/realm_generator/pubspec.yaml
Labels: no-jira-ticket

#1607 RDART-992: Const initializer evaluation is too simple
  CHANGELOG.md
  packages/realm_generator/lib/src/field_element_ex.dart
  packages/realm_generator/test/good_test_data/const_initializer.dart
  packages/realm_generator/test/good_test_data/const_initializer.expected
  packages/realm_generator/test/good_test_data/const_initializer.realm.dart
Labels: cla: yes

#1610 Common setup script
  .github/workflows/setup-runner.yml
Labels: cla: yes
