Repository realm/realm-dart, pull requests merged in 2024-01, with the labels that each got.

#1406 Support maps
  CHANGELOG.md
  common/lib/src/realm_types.dart
  generator/lib/src/dart_type_ex.dart
  generator/lib/src/field_element_ex.dart
  generator/lib/src/realm_field_info.dart
  generator/lib/src/realm_model_info.dart
  generator/test/error_test_data/dict_non_empty_initializer.dart
  generator/test/error_test_data/dict_non_empty_initializer.expected
  generator/test/error_test_data/list_non_empty_initializer.dart
  generator/test/error_test_data/list_non_empty_initializer.expected
  generator/test/error_test_data/map_unsupported.dart
  generator/test/error_test_data/map_unsupported.expected
  generator/test/error_test_data/nullable_list.expected
  generator/test/error_test_data/nullable_list_elements.expected
  generator/test/error_test_data/nullable_realm_value.expected
  generator/test/error_test_data/set_non_empty_initializer.dart
  generator/test/error_test_data/set_non_empty_initializer.expected
  generator/test/error_test_data/unsupported_realm_set_of_nullable_realmobject.expected
  generator/test/error_test_data/unsupported_realm_set_of_nullable_realmvalue.expected
  generator/test/error_test_data/unsupported_realm_set_with_default_values.expected
  generator/test/good_test_data/all_types.dart
  generator/test/good_test_data/all_types.expected
  generator/test/good_test_data/list_initialization.dart
  generator/test/good_test_data/list_initialization.expected
  generator/test/good_test_data/map.dart
  generator/test/good_test_data/map.expected
  lib/src/collections.dart
  lib/src/list.dart
  lib/src/map.dart
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/realm_object.dart
  lib/src/results.dart
  lib/src/set.dart
  test/backlinks_test.dart
  test/geospatial_test.dart
  test/realm_map_test.dart
  test/realm_map_test.g.dart
  test/realm_value_test.dart
  test/results_test.dart
  test/test.dart
Labels: cla: yes

#1463 Remember '?'
  lib/src/app.dart
Labels: no-changelog

#1475 Avoid lib symlink
  flutter/realm_flutter/bin/realm.dart
  flutter/realm_flutter/lib
  flutter/realm_flutter/lib/realm.dart
  flutter/realm_flutter/pubspec.yaml
  flutter/realm_flutter/tests/lib
Labels: no-changelog

#1476 Update lints and ffigen packages
  common/pubspec.yaml
  example/pubspec.yaml
  ffigen/pubspec.yaml
  flutter/realm_flutter/example/pubspec.yaml
  flutter/realm_flutter/tests/pubspec.yaml
  generator/pubspec.yaml
  lib/src/native/realm_bindings.dart
  pubspec.yaml
Labels: no-changelog

#1470 Fix use of http transport from background isolate
  .vscode/launch.json
  .vscode/settings.json
  lib/src/native/realm_bindings.dart
  lib/src/native/realm_core.dart
  lib/src/realm_class.dart
  lib/src/user.dart
  src/dart-dl/dart_api.h
  src/dart-dl/dart_api_dl.h
  src/dart-dl/dart_native_api.h
  src/dart-dl/dart_version.h
  src/realm_dart_sync.cpp
  src/realm_dart_sync.h
  test/app_test.dart
  test/user_test.dart
Labels: no-changelog

#1488 Fix Flutter app build on Linux
  flutter/realm_flutter/linux/CMakeLists.txt
Labels: cla: yes

#1491 Always use persistent handles when passing dart objects as userdata to callbacks
  CHANGELOG.md
  lib/src/native/realm_bindings.dart
  lib/src/native/realm_core.dart
  src/realm_dart.cpp
  src/realm_dart.h
Labels: cla: yes

#1496 kn/mwb/update baseurl
  CHANGELOG.md
  lib/src/app.dart
  lib/src/native/realm_core.dart
  test/app_test.dart
Labels: cla: yes

#1497 We don't always update realm-core in a release
  .github/workflows/prepare-release.yml
Labels: cla: yes, no-changelog

#1498 [Release 1.8.0]
  CHANGELOG.md
  common/pubspec.yaml
  flutter/realm_flutter/example/pubspec.yaml
  flutter/realm_flutter/ios/realm.podspec
  flutter/realm_flutter/macos/realm.podspec
  flutter/realm_flutter/pubspec.yaml
  flutter/realm_flutter/tests/pubspec.yaml
  generator/pubspec.yaml
  lib/src/native/realm_core.dart
  pubspec.yaml
  src/realm_dart.cpp
Labels: cla: yes
